stages:
  - build
  - test
  - staging
  - production

default:
  image: node:current-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules

build api:
  stage: build
  only:
    - master
    - merge_requests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - node_modules
  script:
    - apk add curl
    - npm i --silent
    - npm start &
    - sleep 3
    - curl "http://localhost:3000" | tac | tac | grep -q "Hello World!"

test api:
  stage: test
  services:
    - mongo:latest
  only:
    - master
    - merge_requests
  script:
    - npm test
  tags:
    - mongo

stage api:
  stage: staging
  only:
    - master
  script:
    - apt-get install git
    - git push origin heroku
    - heroku $HEROKU_EMAIL --app=$HEROKU_APP_STAGING
