stages:
  - cache
  - build
  - test

default:
  image: node:current-alpine

.cache_template: &cache
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules

build api:
  stage: build
  only:
    - master
    - merge_requests
  <<: *cache
  cache:
    policy: push
  script:
    - apk add curl
    - npm i
    - npm start &
    - sleep 3
    - curl "http://localhost:3000" | tac | tac | grep -q "Hello World!"

test api:
  stage: test
  only:
    - master
    - merge_requests
  <<: *cache
  cache:
    policy: pull
  script:
    - npm run test
