stages:
  - cache
  - build
  - test

default:
  image: node:current-alpine
#  cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    policy: pull-push
#    paths:
#      - node_modules

update cache:
  stage: cache

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - node_modules/

  script:
    - npm i

build api:
  stage: build
  only:
    - master
    - merge_requests
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules
  script:
    - apk add curl
    - npm start &
    - sleep 3
    - curl "http://localhost:3000" | tac | tac | grep -q "Hello World!"
  artifacts:
    paths:
      - ./node_modules

test api:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - npm run test
