stages:
  - build
  - test

default:
  image: node:current-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - node_modules
  before_script:
    - npm i

build api:
  stage: build
  only:
    - master
    - merge_requests
  cache:
    policy: push
  script:
    - apk add curl
    - npm start &
    - sleep 3
    - curl "http://localhost:3000" | tac | tac | grep -q "Hello World!"

test api:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - npm run test
